### ISSUE TITLE
error in rye build --whell

### ISSUE THREAD

**Issue by markqiu** [DavidVujic/python-polylith#200]
```toml
[project]
name = "profitcube"
version = "0.1.0"
description = "jinniuai's investment power store"
authors = [
    { name = "markqiu", email = "qiucheng@jinniuai.com" }
]
dependencies = [
    "jinja2>=3.1.3",
    "typer>=0.12.2",
    "rich>=13.7.1",
    "numpy>=1.26.4",
    "pydantic>=2.6.4",
    "loguru>=0.7.2",
    "pandas>=2.2.1",
    "pandera>=0.18.3",
    "dolphindb>=3.0.0.0",
    "mootdx>=0.11.4",
    "openpyxl>=3.1.2",
    "mytt>=2.9.3",
    "python-dotenv>=1.0.1",
    "simple-toml-configurator>=1.2.2",
    "croniter>=2.0.3",
    "statsmodels>=0.14.1",
    "pendulum>=3.0.0",
    "pyfinance>=1.3.0",
    "pydantic-extra-types>=2.6.0",
    "backtrader @ https://pypi.jinniuai.com/packages/backtrader/backtrader-1.9.76.123.2.tar.gz",
    "tomli-w>=1.0.0",
    "dynaconf>=3.2.5",
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "polylith-cli>1.5.0",
    "pytest>=8.1.1",
    "ruff>=0.3.7",
    "mypy>=1.9.0",
]


[tool.hatch.build]
dev-mode-dirs = ["components", "bases", "development", "."]


[tool.polylith.bricks]
"bases/profitcube/cli" = "profitcube/cli"
"bases/profitcube/config" = "profitcube/config"
"components/profitcube/core" = "profitcube/core"
"components/profitcube/abilities" = "profitcube/abilities"
"components/profitcube/backtest" = "profitcube/backtest"
"components/profitcube/resources" = "profitcube/resources"
"components/profitcube/utils" = "profitcube/utils"
"components/profitcube/data" = "profitcube/data"
"components/profitcube/可视化" = "profitcube/可视化"
"components/profitcube/services" = "profitcube/services"

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
exclude = [
  ".git",
  ".github",
  "__pycache__",
  ".mypy_cache",
  ".ruff_cache",
  "dist",
  ".venv",
  "./development/*.py",
]
line-length = 120

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[tool.rye.scripts]
ability-create = { call = "profitcube.cli:app" }

```
reproduce command:
`rye build --wheel --sdist` or `rye build --whell`
get the following errors:
```txt
building profitcube
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (hatchling)
* Getting build dependencies for sdist...
* Building sdist...
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (hatchling)
* Getting build dependencies for wheel...
* Building wheel...
Traceback (most recent call last):
  File "/Users/qiucheng/.rye/self/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/Users/qiucheng/.rye/self/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qiucheng/.rye/self/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/rc/m01mh1mn3m99t4879pf_wbk40000gn/T/build-env-qar9yi40/lib/python3.12/site-packages/hatchling/build.py", line 58, in build_wheel
    return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/rc/m01mh1mn3m99t4879pf_wbk40000gn/T/build-env-qar9yi40/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 155, in build
    artifact = version_api[version](directory, **build_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/rc/m01mh1mn3m99t4879pf_wbk40000gn/T/build-env-qar9yi40/lib/python3.12/site-packages/hatchling/builders/wheel.py", line 455, in build_standard
    for included_file in self.recurse_included_files():
  File "/private/var/folders/rc/m01mh1mn3m99t4879pf_wbk40000gn/T/build-env-qar9yi40/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 176, in recurse_included_files
    yield from self.recurse_selected_project_files()
  File "/private/var/folders/rc/m01mh1mn3m99t4879pf_wbk40000gn/T/build-env-qar9yi40/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 180, in recurse_selected_project_files
    if self.config.only_include:
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/rc/m01mh1mn3m99t4879pf_wbk40000gn/T/build-env-qar9yi40/lib/python3.12/site-packages/hatchling/builders/config.py", line 806, in only_include
    only_include = only_include_config.get('only-include', self.default_only_include()) or self.packages
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/rc/m01mh1mn3m99t4879pf_wbk40000gn/T/build-env-qar9yi40/lib/python3.12/site-packages/hatchling/builders/wheel.py", line 240, in default_only_include
    return self.default_file_selection_options.only_include
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qiucheng/.rye/py/cpython@3.12.2/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/rc/m01mh1mn3m99t4879pf_wbk40000gn/T/build-env-qar9yi40/lib/python3.12/site-packages/hatchling/builders/wheel.py", line 228, in default_file_selection_options
    raise ValueError(message)
ValueError: Unable to determine which files to ship inside the wheel using the following heuristics: https://hatch.pypa.io/latest/plugins/builder/wheel/#default-file-selection

The most likely cause of this is that there is no directory that matches the name of your project (profitcube).

At least one file selection option must be defined in the `tool.hatch.build.targets.wheel` table, see: https://hatch.pypa.io/latest/config/build/

As an example, if you intend to ship a directory named `foo` that resides within a `src` directory located at the root of your project, you can define the following:

[tool.hatch.build.targets.wheel]
packages = ["src/foo"]

ERROR Backend subprocess exited when trying to invoke build_wheel
```

By the way: rye build --sdist  can be successful completed.

**Comment by DavidVujic** [comment]
Hi @markqiu!

It looks like you are trying to build the development pyproject that is in the root of the repo. The recommended way in Polylith is to build artifacts from the `projects`. The Development area is used during development, and when running services or apps locally. All code, all bases (entry points) and all components is added in the development project. But when building things that should be installed somewhere, you should use a project that likely only has one base (one entry point).

The `pyproject.toml` in a project should have the the "hatch-polylith-bricks" hook (the one we found out shouldn't be in the root project).

You can create projects with the `rye run poly create project --name <your-project-name-here>` and it will create a project-specific `pyproject.toml` for you.

To build a wheel in a project, you can use the Rye option `--pyproject` for it, such as
```
rye build --pyproject projects/your-project-folder-here/pyproject.toml --wheel
```

I hope this helps!
